### ISSUE TITLE
Exercise 2: jQuery basic concepts

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JQ-Track#1]
https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/sandbox.js

You should understand how to select and manipulate elements.

2.1 Selecting
Open the file /exercises/index.html in your browser. Use the file /exercises/js/sandbox.js to accomplish the following:
Select all of the div elements that have a class of “module”.
Come up with three selectors that you could use to get the third item in the #myList unordered list. Which is the best to use? Why?
Select the label for the search input using an attribute selector.
Figure out how many elements on the page are hidden
Figure out how many image elements on the page have an alt attribute.
Select all of the odd table rows in the table body.

2.2 Traversing
Open the file /exercises/index.html in your browser. Use the file /exercises/js/sandbox.js to accomplish the following:
Select all of the image elements on the page; log each image’s alt attribute.
Select the search input text box, then traverse up to the form and add a class to the form.
Select the list item inside #myList that has a class of “current” and remove that class from it; add a class of “current” to the next list item.
Select the select element inside #specials; traverse your way to the submit button.
Select the first list item in the #slideshow element; add the class “current” to it, and then add a class of “disabled” to its sibling elements.

2.3 Manipulating
Open the file /exercises/index.html in your browser. Use the file /exercises/js/sandbox.js to accomplish the following:
Add five new list items to the end of the unordered list #myList.
Remove the odd list items
Add another h2 and another paragraph to the last div.module
Add another option to the select element; give the option the value “Wednesday” 
Add a new div.module to the page after the last one; put a copy of one of the existing images inside of it.

**Comment by segunadeleye** [comment]
- Use 2-space indentation
- Please add a link to the javascript file.

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
- For the question; Come up with three selectors that you could use to get the third item in the #myList unordered list - The first one is not the best.
- jQuery object variables should be preceded by `$`
  `$images = $('img');`
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/sandbox.js#L70
  Is the attribute selector needed here?
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/sandbox.js#L74
  This can be done in fewer DOM traversal
  Use single chaining.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/sandbox.js#L82
  You don't have to loop. You can directly call `addClass` on the siblings.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/sandbox.js#L92
  There is a lot of hits on the DOM, one for each list. Build the new lists and drop them in the DOM once. It is good practice to hit the DOM in as fewer times as possible. This is good for optmisation.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/sandbox.js#L103
  Use jQuery objects instead of string to create new DOM elements
  `apend()` can take multiple arguments.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/sandbox.js#L108
  Is the attribute selector needed here?
  Use jQuery objects instead of string to create new DOM elements
  Wednesday should come after Tuesday
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/sandbox.js#L111
  Use single chaining.

**Comment by damilola-dealdey** [comment]
Redone

**Comment by segunadeleye** [comment]
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/sandbox.js#L65-L66
  Do this in one chain.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/sandbox.js#L79-L82
  Do this in one chain
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/sandbox.js#L82
  There is no need to do this `$($siblings)`. `$siblings` is already a jQuery object.

**Comment by damilola-dealdey** [comment]
Changes Made

**Comment by segunadeleye** [comment]
All good
