### ISSUE TITLE
Exercise 5 : Effects

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JQ-Track#3]
https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/blog.js
https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/slideshow.js
https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/navigation.js

You should understand jQuery built in effects, adding delays to effects and $.fn.animate

5.1 Reveal hidden text.
Open the file /exercises/index.html in your browser. Use the file /exercises/js/blog.js. Your task is to add some interactivity to the blog section of the page. The spec for the feature is as follows:
Clicking on a headline in the #blog div should slide down the excerpt paragraph
Clicking on another headline should slide down its excerpt paragraph, and slide up any other currently showing excerpt paragraphs.

5.2 Create Drop down menus.
Open the file /exercises/index.html in your browser. Use the file /exercises/js/navigation.js. Your task is to add dropdowns to the main navigation at the top of the page.
Hovering over an item in the main menu should show that item's submenu items, if any.
Exiting an item should hide any submenu items.

To accomplish this, use the $.fn.hover method to add and remove a class from the submenu items to control whether they're visible or hidden. (The file at /exercises/css/styles.css includes the "hover" class for this purpose). You might want to change the CSS files a little bit for this exercise.

5.3 Create a Slideshow
This is a tough one if you do not know JS basics and particularly scopes. Open the file /exercises/index.html in your browser. Use the file /exercises/js/slideshow.js. Your task is to take a plain semantic HTML page and enhance it with JavaScript by adding a slideshow.
Move the #slideshow element to the top of the body.
Write code to cycle through the list items inside the element; fade one in, display it for a few seconds, then fade it out and fade in the next one.
When you get to the end of the list, start again at the beginning.
For an extra challenge, create a navigation area under the slideshow that shows how many images there are and which image you're currently viewing. (Hint: $.fn.prevAll will come in handy for this.)

**Comment by segunadeleye** [comment]
- Use 2-space indentation
- Please add a link to the javascript file.

**Comment by damilola-dealdey** [comment]
Done

**Comment by segunadeleye** [comment]
### blog.js
- Fix the indentation
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/blog.js#L7
  Do you have to go through `ul` and `li` to get `h3`? Note that `find()` is fast for descendants lookup.
  You don't need to loop.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/blog.js#L10
  You can use something else to select the `p` element.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/blog.js#L12
  You don't have to traverse this way to get to the other `p` elements. You can do this in much fewer steps.

**Comment by segunadeleye** [comment]
### navigation.js
- Fix the indentation.
- These can be done in one chain.

```
$(this).addClass('hover');
$(this).children('ul')
       .addClass('see');
```

and

```
$(this).removeClass('hover');
$(this).children('ul')
       .removeClass('see');
```

**Comment by segunadeleye** [comment]
### slideshow.js
- Use the correct convention for jQuery object variables.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/slideshow.js#L2
  Do you have to use `eq(0)` here?
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/slideshow.js#L3 and https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/slideshow.js#L56
  Use `find` instead of `children`. `find` is faster for selecting descendants/children
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/slideshow.js#L4
  Since `this.newDiv` is only used with the `init` method, why declare it as an instance variable?
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/slideshow.js#L8 and https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/slideshow.js#L9
  How about moving these into the `init` method.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/slideshow.js#L34
  How about `var imageSrc;` in place of `var imageSrc = '';`
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/slideshow.js#L36
  Why this?
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/slideshow.js#L39, https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/slideshow.js#L42, https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/slideshow.js#L47 and https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/slideshow.js#L56
  Since you have just one `img` element in each `li` element, there is no need for the pseudo `:first`.
  Note that `:first` and `eq(0)` are needed to select the first element if and only if multiple elements in the current DOM meet the selector, otherwise, you can call the jQuery method directly on the returned jQuery object without `:first` or `eq(0)`.

**Comment by damilola-dealdey** [comment]
All Redone

**Comment by segunadeleye** [comment]
All of them look fine.
