### ISSUE TITLE
Exercise 7

### ISSUE THREAD

**Issue by damilola-dealdey** [damilola-dealdey/JQ-Track#5]
https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/product_grid.js
https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/delegate.js

Product Grid Exercise (with json data provided)
We have product data in CSV format and images as follows. Given the CSV file and images at this url - http://dl.dropbox.com/u/628209/exercises/javascript/product_data.tar.gz.
Here is the JSON for the same data. http://dl.dropbox.com/u/628209/exercises/javascript/product.json.

Create a page which loads this JSON data and renders a store front. All the products should be displayed by default. Show a list of Brands in the left. Upon clicking the checkbox in front of a brand, only that particular brand products should be show, hide all others. If no checkbox is selected show products belonging to all brands. Similarly have a filter for color. Also create a toggle for “All Products” and “Available Products”. If a user clicks “Available Products”, show only products that are not sold out. Note that the filters should work together, so I should be able to see Only Yellow products of Brand C which are Available.

.delegate() / .on() exercise
Create a stack of divs. Initially an empty container should display, a button on right side say "Add Item", should add a div to the stack with an incremental number(starting from 1). Clicking any item in the stack should highlight that item. Clicking the last item on the stack should remove that item from the stack.
HINT: Use jQuery delegate. live() method has been removed from the latest version of jQuery so you may want to use on() or delegate().

**Comment by segunadeleye** [comment]
### delegate.js
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/delegate.js#L42
  Don't create variables if you will not be using them
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/delegate.js#L8-L9
  Move this into the constructor. Always do things like this in the constructor.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/delegate.js#L15
  Why not just pass the jquery object as the argument since that is what you are using in the `hit()` method.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/delegate.js#L14
  It's better to delegate this event to the closest parent.
- Based on the javascript convention, always use single quotes for strings. Use double quotes only when you have single quote in the string.

**Comment by segunadeleye** [comment]
### product_grid.js
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/product_grid.js#L9-L10
Move these into the contructore

- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/product_grid.js#L11
You don't need to iterate

- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/delegate.js#L110
Don't create variables if you will not be using them

**Comment by segunadeleye** [comment]
### product_grid.js
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/product_grid.js#L9-L10
  Move these into the contructor.
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/product_grid.js#L11
  You don't need to iterate
- https://github.com/damilola-dealdey/JQ-Track/blob/master/exercises/js/delegate.js#L110
  Don't create variables if you will not be using them.

**Comment by segunadeleye** [comment]
In addition to the comments above, use the correct naming convention for jQuery object variables.

**Comment by damilola-dealdey** [comment]
Redone

**Comment by segunadeleye** [comment]
All good!
